name: UMBC_capstone_2022
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - ipywidgets=7.7.0
  - matplotlib=3.5.1
  - nltk=3.5
  - notebook=6.4.8
  - numpy=1.21.2
  - pandas=1.4.1
  - pip=21.2.4
  - python=3.9.7
  - pytorch=1.11.0
  - seaborn=0.11.2
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pip:
    - ipywidgets==7.7.0
    - nltk==3.7
    - scikit-learn==1.0.2
    - transformers==4.11.3
    - yfinance==0.1.70