name: UMBC_capstone_2022
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.4.1
  - matplotlib=3.5.1
  - notebook=6.4.8
  - numpy=1.21.2
  - pandas=1.4.1
  - pip=21.2.4
  - python=3.9.7
  - pytorch=1.11.0
  - seaborn=0.11.2
  - torchaudio=0.11.0
  - torchvision=0.12.0
